spring:
  application:
    name: Reservation-system

  profiles:
    active: dev

  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    info:
      access: READ_ONLY
    health:
      access: READ_ONLY
    metrics:
      access: READ_ONLY
