spring.application.name=Kamann-modular

spring.profiles.active=dev

management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.info.access=read_only
info.app.name=Kamann
info.app.description=Modular reservation system
info.app.version=0.0.1